title: CTFLAbs
description: "This is the home for WriteUps and Walkthroughs of Capture the flag events or similar boxes/machines."
author:
  name: "krAshwin"
  email: "krashwin00@gmail.com"
  twitter_username: OkAshwin

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Custom variables
owner : "cardinal"
year : "2020"
